import Link from 'next/link';

export default function Terms() {
  return (
    <div style={{background: 'var(--black)', minHeight: '100vh'}}>
      <main style={{maxWidth: '800px', margin: '0 auto', padding: '40px 24px 80px'}}>

        <div style={{marginBottom: '40px'}}>
          <h1 style={{fontFamily: 'Cormorant Garamond, serif', fontSize: '48px', fontWeight: 600, color: 'var(--off-white)', marginBottom: '12px'}}>Terms of <span style={{color: 'var(--gold)'}}>Use</span></h1>
          <p style={{fontSize: '14px', color: 'var(--text-muted)', fontWeight: 300}}>Last updated: March 2026</p>
        </div>

        {[
          {
            title: '1. Acceptance of Terms',
            content: 'By accessing and using Firm Law AI, you agree to be bound by these Terms of Use. If you do not agree, please do not use this platform.'
          },
          {
            title: '2. Nature of Service',
            content: 'Firm Law AI provides general legal information powered by artificial intelligence. The information provided is for educational and informational purposes only and does not constitute legal advice. We are not a law firm and do not provide legal representation.'
          },
          {
            title: '3. Not a Substitute for Legal Advice',
            content: 'The content generated by Firm Law AI should not be relied upon as a substitute for professional legal advice from a qualified advocate or solicitor. Always consult a licensed legal professional for advice specific to your situation.'
          },
          {
            title: '4. Accuracy of Information',
            content: 'While we strive to provide accurate and up-to-date information, we make no warranties regarding the completeness, accuracy, or reliability of any content. Indian laws are subject to amendment and our AI may not reflect the most recent changes.'
          },
          {
            title: '5. User Responsibilities',
            content: 'You agree to use Firm Law AI only for lawful purposes. You must not misuse the platform to generate fraudulent documents, harass others, or violate any applicable laws. You are responsible for verifying any documents generated before filing them with any authority.'
          },
          {
            title: '6. Intellectual Property',
            content: 'The Firm Law AI platform, its design, and branding are the intellectual property of its creators. AI-generated content provided to you may be used for personal and non-commercial purposes.'
          },
          {
            title: '7. Limitation of Liability',
            content: 'Firm Law AI and its creators shall not be liable for any damages arising from the use or inability to use this service, including any reliance on AI-generated legal content.'
          },
          {
            title: '8. Changes to Terms',
            content: 'We reserve the right to modify these terms at any time. Continued use of the platform after changes constitutes acceptance of the new terms.'
          },
          {
            title: '9. Contact',
            content: 'For any questions regarding these terms, please contact us through our Contact page.'
          },
        ].map((section, i) => (
          <div key={i} style={{background: 'var(--black-card)', border: '1px solid var(--border)', borderRadius: '12px', padding: '24px', marginBottom: '12px'}}>
            <h2 style={{fontFamily: 'Cormorant Garamond, serif', fontSize: '20px', fontWeight: 600, color: 'var(--gold)', marginBottom: '12px'}}>{section.title}</h2>
            <p style={{fontSize: '13px', color: 'var(--text-muted)', lineHeight: 1.9, fontWeight: 300}}>{section.content}</p>
          </div>
        ))}

        <div style={{marginTop: '32px', display: 'flex', gap: '12px', flexWrap: 'wrap'}}>
          <Link href="/privacy" style={{background: 'transparent', color: 'var(--gold)', padding: '12px 28px', borderRadius: '8px', fontSize: '13px', fontWeight: 600, textDecoration: 'none', border: '1px solid rgba(201,168,76,0.3)'}}>View Privacy Policy</Link>
          <Link href="/" style={{background: 'linear-gradient(135deg, var(--gold), var(--gold-dim))', color: 'var(--black)', padding: '12px 28px', borderRadius: '8px', fontSize: '13px', fontWeight: 600, textDecoration: 'none'}}>Back to Home</Link>
        </div>

      </main>
    </div>
  );
}