'use client';
import { useState } from 'react';
import LanguageToggle from '../components/LanguageToggle';

const categories = [
  { id: 'consumer', icon: '🛒', label: 'Consumer & Shopping' },
  { id: 'property', icon: '🏠', label: 'Property & Rent' },
  { id: 'employment', icon: '👷', label: 'Employment & Salary' },
  { id: 'family', icon: '👨‍👩‍👧', label: 'Family & Marriage' },
  { id: 'criminal', icon: '👮', label: 'Criminal & Police' },
  { id: 'cyber', icon: '💻', label: 'Cyber Crime & Fraud' },
  { id: 'medical', icon: '🏥', label: 'Medical & Hospital' },
  { id: 'other', icon: '⚖️', label: 'Other Legal Issue' },
];

const inputBox = {
  width: '100%',
  background: '#1a1a1a',
  border: '2px solid rgba(201,168,76,0.5)',
  borderRadius: '8px',
  padding: '14px',
  fontSize: '14px',
  color: '#f5f0e8',
  outline: 'none',
  fontFamily: 'Outfit, sans-serif',
};

export default function LegalProblemSolver() {
  const [step, setStep] = useState(1);
  const [category, setCategory] = useState(null);
  const [situation, setSituation] = useState('');
  const [desiredOutcome, setDesiredOutcome] = useState('');
  const [location, setLocation] = useState('');
  const [solution, setSolution] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [language, setLanguage] = useState('english');

  async function solveProblem() {
    if (!situation.trim()) return;
    setLoading(true);
    setSolution('');
    setError('');
    setCopied(false);

    const prompt = `You are an expert Indian legal advisor. A person has the following legal problem:

Category: ${category?.label || 'General Legal Issue'}
Location: ${location || 'India'}
Situation: ${situation}
Desired Outcome: ${desiredOutcome || 'Not specified'}

Please provide a comprehensive legal solution in the following format:

1. SITUATION ANALYSIS
Analyse their legal situation and identify the key legal issues.

2. APPLICABLE LAWS & RIGHTS
List all relevant Indian Acts, sections, and legal rights that apply to this situation.

3. STEP-BY-STEP ACTION PLAN
Provide a clear, numbered action plan they should follow immediately.

4. DOCUMENTS REQUIRED
List all documents they need to gather or prepare.

5. AUTHORITY TO APPROACH
Specify which court, tribunal, forum, or authority they should approach.

6. TIME LIMITS (LIMITATION PERIOD)
Mention any important deadlines or limitation periods they must be aware of.

7. ESTIMATED OUTCOME
Give a realistic assessment of likely outcomes if they follow this plan.

8. IMPORTANT WARNINGS
Any important cautions or things to avoid.

Be practical, specific, and actionable. Focus on Indian law only.`;

    try {
      const res = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: prompt, mode: 'qa', language }),
      });
      const data = await res.json();
      if (data.error) setError(data.error);
      else { setSolution(data.response); setStep(3); }
    } catch {
      setError('Something went wrong. Please try again.');
    }
    setLoading(false);
  }

  function copySolution() {
    navigator.clipboard.writeText(solution);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function printSolution() {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Legal Solution — Firm Law AI</title>
          <style>
            body { font-family: 'Times New Roman', serif; font-size: 14px; line-height: 1.8; margin: 40px; color: #000; }
            h1 { font-size: 20px; text-align: center; margin-bottom: 4px; }
            .subtitle { text-align: center; font-size: 12px; color: #555; margin-bottom: 32px; }
            pre { white-space: pre-wrap; font-family: 'Times New Roman', serif; font-size: 14px; line-height: 1.8; }
            .footer { margin-top: 40px; font-size: 11px; color: #888; border-top: 1px solid #ccc; padding-top: 12px; text-align: center; }
            @media print { .no-print { display: none; } }
          </style>
        </head>
        <body>
          <h1>Legal Problem Solution</h1>
          <div class="subtitle">Generated by Firm Law AI — ${new Date().toLocaleDateString('en-IN', {day: 'numeric', month: 'long', year: 'numeric'})}</div>
          <pre>${solution}</pre>
          <div class="footer">This solution was AI-generated by Firm Law AI. Please consult a qualified advocate before taking legal action.</div>
          <div class="no-print" style="margin-top:20px; text-align:center;">
            <button onclick="window.print()" style="padding:10px 24px; background:#c9a84c; border:none; border-radius:6px; font-size:14px; cursor:pointer; font-weight:600;">🖨️ Print / Save as PDF</button>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
  }

  function reset() {
    setStep(1);
    setCategory(null);
    setSituation('');
    setDesiredOutcome('');
    setLocation('');
    setSolution('');
    setError('');
  }

  return (
    <div style={{background: 'var(--black)', minHeight: '100vh'}}>
      <main style={{maxWidth: '800px', margin: '0 auto', padding: '40px 20px 80px'}}>

        {/* Header */}
        <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '32px', flexWrap: 'wrap', gap: '16px'}}>
          <div>
            <h1 style={{fontFamily: 'Cormorant Garamond, serif', fontSize: '36px', fontWeight: 600, color: 'var(--off-white)', marginBottom: '8px'}}>🔎 Legal Problem Solver</h1>
            <p style={{fontSize: '14px', color: 'var(--text-muted)', fontWeight: 300}}>Describe your situation and get a complete legal action plan.</p>
          </div>
          <LanguageToggle language={language} setLanguage={setLanguage} />
        </div>

        {/* Progress Steps */}
        <div style={{display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '32px'}}>
          {[
            { num: 1, label: 'Category' },
            { num: 2, label: 'Your Situation' },
            { num: 3, label: 'Solution' },
          ].map((s, i) => (
            <div key={s.num} style={{display: 'flex', alignItems: 'center', gap: '8px', flex: i < 2 ? 1 : 'none'}}>
              <div style={{display: 'flex', alignItems: 'center', gap: '8px'}}>
                <div style={{
                  width: '32px', height: '32px', borderRadius: '50%',
                  background: step >= s.num ? 'linear-gradient(135deg, var(--gold), var(--gold-dim))' : 'var(--black-card)',
                  border: step >= s.num ? 'none' : '1px solid var(--border)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: '13px', fontWeight: 700,
                  color: step >= s.num ? 'var(--black)' : 'var(--text-dim)',
                  flexShrink: 0
                }}>{s.num}</div>
                <span style={{fontSize: '12px', color: step >= s.num ? 'var(--gold)' : 'var(--text-dim)', fontWeight: step >= s.num ? 600 : 400, whiteSpace: 'nowrap'}}>{s.label}</span>
              </div>
              {i < 2 && <div style={{flex: 1, height: '1px', background: step > s.num ? 'var(--gold)' : 'var(--border)', minWidth: '20px'}}/>}
            </div>
          ))}
        </div>

        {/* STEP 1 — Category */}
        {step === 1 && (
          <div>
            <p style={{fontSize: '13px', color: 'var(--text-muted)', marginBottom: '20px', fontWeight: 300}}>Select the category that best describes your legal problem:</p>
            <div style={{display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '12px'}}>
              {categories.map(cat => (
                <div key={cat.id}
                  onClick={() => { setCategory(cat); setStep(2); }}
                  style={{background: 'var(--black-card)', border: '1px solid var(--border)', borderRadius: '14px', padding: '24px 16px', cursor: 'pointer', textAlign: 'center', transition: 'all 0.2s'}}>
                  <div style={{fontSize: '32px', marginBottom: '12px'}}>{cat.icon}</div>
                  <p style={{fontSize: '13px', fontWeight: 600, color: 'var(--off-white)'}}>{cat.label}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* STEP 2 — Situation Form */}
        {step === 2 && (
          <div>
            <button onClick={() => setStep(1)}
              style={{fontSize: '13px', color: 'var(--gold)', background: 'transparent', border: 'none', cursor: 'pointer', marginBottom: '24px', fontFamily: 'Outfit, sans-serif'}}>
              ← Change category
            </button>

            <div style={{background: 'var(--black-card)', border: '1px solid var(--border)', borderRadius: '16px', padding: '28px'}}>
              <div style={{display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '24px', paddingBottom: '16px', borderBottom: '1px solid var(--border)'}}>
                <span style={{fontSize: '28px'}}>{category?.icon}</span>
                <div>
                  <h2 style={{fontFamily: 'Cormorant Garamond, serif', fontSize: '22px', fontWeight: 600, color: 'var(--off-white)'}}>{category?.label}</h2>
                  <p style={{fontSize: '12px', color: 'var(--text-dim)'}}>Describe your situation in detail</p>
                </div>
              </div>

              <div style={{display: 'flex', flexDirection: 'column', gap: '24px'}}>

                {/* Situation */}
                <div>
                  <label style={{display: 'block', fontSize: '13px', fontWeight: 600, color: 'var(--off-white)', marginBottom: '10px'}}>
                    📝 Describe Your Situation <span style={{color: 'var(--gold)'}}>*</span>
                  </label>
                  <textarea
                    value={situation}
                    onChange={e => setSituation(e.target.value)}
                    placeholder="e.g. I ordered a laptop from an online store worth ₹45,000. The product arrived damaged and when I requested a refund, the company is refusing to process it. It has been 3 weeks now..."
                    rows={6}
                    style={{...inputBox, resize: 'none', lineHeight: 1.7}}
                  />
                  <p style={{fontSize: '11px', color: 'var(--text-dim)', marginTop: '6px'}}>💡 Include dates, amounts, names of parties, and what has happened so far.</p>
                </div>

                {/* Desired Outcome */}
                <div>
                  <label style={{display: 'block', fontSize: '13px', fontWeight: 600, color: 'var(--off-white)', marginBottom: '10px'}}>
                    🎯 What outcome do you want?
                  </label>
                  <input
                    type="text"
                    value={desiredOutcome}
                    onChange={e => setDesiredOutcome(e.target.value)}
                    placeholder="e.g. Full refund of ₹45,000 + compensation for mental harassment"
                    style={inputBox}
                  />
                </div>

                {/* Location */}
                <div>
                  <label style={{display: 'block', fontSize: '13px', fontWeight: 600, color: 'var(--off-white)', marginBottom: '10px'}}>
                    📍 Your State / City
                  </label>
                  <input
                    type="text"
                    value={location}
                    onChange={e => setLocation(e.target.value)}
                    placeholder="e.g. Hyderabad, Telangana"
                    style={inputBox}
                  />
                </div>

              </div>

              {error && (
                <div style={{marginTop: '16px', background: 'rgba(255,50,50,0.05)', border: '1px solid rgba(255,50,50,0.2)', borderRadius: '8px', padding: '12px', fontSize: '13px', color: '#ff6b6b'}}>❌ {error}</div>
              )}

              <button onClick={solveProblem} disabled={loading || !situation.trim()}
                style={{marginTop: '28px', width: '100%', padding: '16px', background: loading || !situation.trim() ? 'rgba(201,168,76,0.3)' : 'linear-gradient(135deg, var(--gold), var(--gold-dim))', color: 'var(--black)', border: 'none', borderRadius: '10px', fontSize: '15px', fontWeight: 700, cursor: loading || !situation.trim() ? 'not-allowed' : 'pointer', fontFamily: 'Outfit, sans-serif', letterSpacing: '0.5px'}}>
                {loading ? '⏳ Analysing your situation...' : '🔎 Get My Legal Solution'}
              </button>
            </div>
          </div>
        )}

        {/* Loading */}
        {loading && (
          <div style={{background: 'var(--black-card)', border: '1px solid var(--border)', borderRadius: '16px', padding: '56px 48px', textAlign: 'center', marginTop: '20px'}}>
            <div style={{width: '56px', height: '56px', border: '3px solid rgba(201,168,76,0.2)', borderTop: '3px solid var(--gold)', borderRadius: '50%', margin: '0 auto 24px', animation: 'spin 1s linear infinite'}}/>
            <p style={{fontFamily: 'Cormorant Garamond, serif', fontSize: '24px', color: 'var(--off-white)', marginBottom: '8px'}}>Analysing your legal situation...</p>
            <p style={{fontSize: '13px', color: 'var(--text-dim)', fontWeight: 300, maxWidth: '360px', margin: '0 auto'}}>Researching applicable Indian laws, relevant case precedents, and preparing your action plan</p>
            <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
          </div>
        )}

        {/* STEP 3 — Solution */}
        {step === 3 && solution && (
          <div>
            <button onClick={reset}
              style={{fontSize: '13px', color: 'var(--gold)', background: 'transparent', border: 'none', cursor: 'pointer', marginBottom: '24px', fontFamily: 'Outfit, sans-serif'}}>
              ← Solve another problem
            </button>

            <div style={{background: 'linear-gradient(135deg, rgba(201,168,76,0.1), rgba(201,168,76,0.05))', border: '1px solid rgba(201,168,76,0.3)', borderRadius: '16px', padding: '24px 28px', marginBottom: '20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '16px'}}>
              <div style={{display: 'flex', alignItems: 'center', gap: '14px'}}>
                <div style={{width: '44px', height: '44px', background: 'linear-gradient(135deg, var(--gold), var(--gold-dim))', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '20px', flexShrink: 0}}>⚖️</div>
                <div>
                  <h2 style={{fontFamily: 'Cormorant Garamond, serif', fontSize: '22px', fontWeight: 600, color: 'var(--off-white)', marginBottom: '3px'}}>Your Legal Solution</h2>
                  <p style={{fontSize: '12px', color: 'var(--text-dim)'}}>{category?.label} — Firm Law AI</p>
                </div>
              </div>
              <div style={{display: 'flex', gap: '8px'}}>
                <button onClick={copySolution}
                  style={{fontSize: '12px', padding: '8px 16px', borderRadius: '8px', background: copied ? 'rgba(201,168,76,0.2)' : 'transparent', border: '1px solid rgba(201,168,76,0.3)', color: 'var(--gold)', cursor: 'pointer', fontFamily: 'Outfit, sans-serif'}}>
                  {copied ? '✅ Copied!' : '📋 Copy'}
                </button>
                <button onClick={printSolution}
                  style={{fontSize: '12px', padding: '8px 16px', borderRadius: '8px', background: 'linear-gradient(135deg, var(--gold), var(--gold-dim))', border: 'none', color: 'var(--black)', cursor: 'pointer', fontWeight: 600, fontFamily: 'Outfit, sans-serif'}}>
                  🖨️ Print / Save
                </button>
              </div>
            </div>

            <div style={{background: 'var(--black-card)', border: '1px solid var(--border)', borderRadius: '16px', padding: '28px'}}>
              <div style={{fontSize: '14px', lineHeight: 1.9, color: 'var(--text-muted)', whiteSpace: 'pre-wrap', fontWeight: 300}}>
                {solution}
              </div>
              <div style={{marginTop: '24px', background: 'rgba(201,168,76,0.04)', border: '1px solid rgba(201,168,76,0.15)', borderRadius: '8px', padding: '16px'}}>
                <p style={{fontSize: '12px', color: 'rgba(201,168,76,0.7)', lineHeight: 1.7}}>
                  ⚠️ <strong style={{color: 'var(--gold)'}}>Important:</strong> This solution is AI-generated based on general Indian law. Always consult a qualified advocate before taking legal action.
                </p>
              </div>
            </div>

            <div style={{display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '12px', marginTop: '20px'}}>
              {[
                { icon: '📄', label: 'Draft a Document', href: '/draft' },
                { icon: '💬', label: 'Ask a Follow-up', href: '/legal-qa' },
                { icon: '🏛️', label: 'Browse Laws', href: '/laws' },
              ].map((action, i) => (
                <a key={i} href={action.href} style={{background: 'var(--black-card)', border: '1px solid var(--border)', borderRadius: '12px', padding: '16px', textAlign: 'center', textDecoration: 'none', display: 'block'}}>
                  <div style={{fontSize: '24px', marginBottom: '8px'}}>{action.icon}</div>
                  <p style={{fontSize: '12px', fontWeight: 600, color: 'var(--text-muted)'}}>{action.label}</p>
                </a>
              ))}
            </div>
          </div>
        )}

      </main>
    </div>
  );
}